### PR TITLE
Here is our code of conduct. Let us not simply add the Contributor Co…

### PR DESCRIPTION
**Pull request by nawedx**
…venant to our project and assume that any problems with civility, harassment, or discrimination will be solved. As project maintainers, we must be committed to enforcing the code of conduct.

Before adopting the Contributor Covenant let us take the time to discuss and decide how to deal with the problems.

Morality cannot be legislated, but behaviour can be regulated.
by Dr Martin Luther King, Jr.

### CODE REVIEW

**Review by knrt10 — APPROVED** [review]
+1 👍 LGTM

**Comment by knrt10** [comment]
@itsmepiyush2 check for any spelling or grammatical mistakes

**Comment by nawedx** [comment]
> @itsmepiyush2 check for any spelling mistakes

There won't be any it is from https://www.contributor-covenant.org/

**Comment by knrt10** [comment]
> > @itsmepiyush2 check for any spelling mistakes
> 
> There won't be any it is from https://www.contributor-covenant.org/

cool

**Comment by nawedx** [comment]
@knrt10 ask for review from all psoc members in all three years.

**Comment by knrt10** [comment]
Bhai sahi hei. Sab akar apne aap review kar deinge. Ye auto generated file hei so errors ke chance nhi hei. Baki isse jyada abhi zaroorat nhi, agar aur kuch add karna hua baad mei kar deinge.

**Comment by nawedx** [comment]
@p-society/2019-batch @p-society/2020-batch @p-society/2021-batch 
You are requested to review the changes.

**Review by piyushmishra12 — APPROVED** [review]

**Review by Rupeshiya — APPROVED** [review]
Looks good !!

**Review by debck — APPROVED** [review]

**Pull request merged**
